### ISSUE TITLE
Extend Interface

### ISSUE THREAD

**Issue by Saikurin** [diablomedia/phpunit-pretty-printer#117]
When i added line 

```xml
printerClass="DiabloMedia\PHPUnit\Printer\PrettyPrinter"
```

I have this error :

```error
Fatal error: Class DiabloMedia\PHPUnit\Printer\PrettyPrinter cannot extend from interface PHPUnit\TextUI\ResultPrinter in /app/cookingblog/vendor/diablomedia/phpunit-pretty-printer/src/DiabloMedia/PHPUnit/Printer/PrettyPrinter.php on line 5
```

I used this library with Symfony 5.3 and PHPUnit 9.5.6 and phpunit-pretty-printer 2.0

**Comment by jaydiablo** [comment]
Hi @Saikurin, this issue happens due to a change in PHPUnit 9, which this printer isn't compatible with yet.

We do have a PR drafted to add PHPUnit 9 support (#93) that needs some testing.

Do you think you would be able to install from that branch and test it out with your project?

In your `composer.json` change

```
"diablomedia/phpunit-pretty-printer": "^4.0.1",
```

to

```
"diablomedia/phpunit-pretty-printer": "dev-phpunit-9 as 4.0.1",
```

And update your dependencies with `composer update diablomedia/phpunit-pretty-printer`.

**Comment by Saikurin** [comment]
Hi @jaydiablo,

Sorry for taking time to test the branch.

Well, everything seems ok. Maybe just a readjustment on the test display with a return to the beginning of the line?

![image](https://user-images.githubusercontent.com/11704898/134139935-bc400d0e-93f3-4ae1-8eb7-1115db38aa76.png)

I also have a Notice type message in the screenshot

Nice job

**Comment by jaydiablo** [comment]
PHPUnit support has been released in version 5.
