### ISSUE TITLE
Could not use "DiabloMedia\PHPUnit\Printer\PrettyPrinter" as printer.

### ISSUE THREAD

**Issue by l1br3** [diablomedia/phpunit-pretty-printer#7]
Hi,

I get this Error when I try to use the printer:
`Could not use "DiabloMedia\PHPUnit\Printer\PrettyPrinter" as printer.`

With the command :   
`phpunit includes/t_tests --verbose --test-suffix test.php --colors=always --debug --printer 'DiabloMedia\PHPUnit\Printer\PrettyPrinter'`

Used with php 7 and PHPUnit 6.0.10.

I did the install with composer from my project directory as said in README.

It seems to come from [here](https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/Command.php#L846)

Thanks

**Comment by aripringle** [comment]
Thanks for the report. I think this is probably because you're running phpunit from a non-composer installation. This library currently assumes that you're running PHPUnit from a composer installation (and even requires it as a package), ie:
```vendor/bin/phpunit --printer 'DiabloMedia\PHPUnit\Printer\PrettyPrinter' ...```

If you'd rather use a phpunit package that is installed elsewhere, you'll probably need to create a bootstrap file for your tests that includes the composer autoloader:
```require __DIR__ . '/vendor/autoload.php';```

A quick and dirty way to test this seems to be to use the composer autoloader AS the bootstrap:
```./phpunit.phar --colors=always --bootstrap vendor/autoload.php --printer 'DiabloMedia\PHPUnit\Printer\PrettyPrinter' ...```

I'll need to update the documentation to mention this. Let me know if this doesn't solve your issue though.

**Comment by l1br3** [comment]
Works perfectly ! 

I changed command to :  
`php vendor/bin/phpunit includes/t_tests --verbose --test-suffix test.php --colors=always --debug --printer 'DiabloMedia\PHPUnit\Printer\PrettyPrinter'`

Tank you very much for your rapidity !

**Comment by l1br3** [comment]
[PR if you want](https://github.com/diablomedia/phpunit-pretty-printer/pull/8)
